main = "./src/index.ts"
name = "gitbook-open-cache"
compatibility_date = "2024-09-02"

[observability]
enabled = true
head_sampling_rate = 0.1

durable_objects.bindings = [
  {name = "CACHE", class_name = "CacheObject"}
]

migrations = [
  {tag = "v1", new_classes = ["CacheObject"]}
]

[env.preview]
name = "gitbook-open-cache-preview"
durable_objects.bindings = [
  {name = "CACHE", class_name = "CacheObject"}
]

[env.preview.observability]
enabled = true
head_sampling_rate = 1
